[build]
  publish = "_site"
  command = "./build.sh"

[build.environment]
  HUGO_VERSION = "0.62.2"

[[redirects]]
  from = "/security.html"
  to = "/security/"
  status = 301

[[redirects]]
  from = "https://syncthing.org/"
  to = "https://syncthing.net/foundation/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.syncthing.org/"
  to = "https://syncthing.net/foundation/"
  status = 301
  force = true
